import jsPDF from 'jspdf';
import 'jspdf-autotable';

/**
 * Export route details to PDF
 * @param {Object} route - The route object containing details and stops
 */
export const exportToPDF = (route) => {
  try {
    if (!route) {
        console.error("No route data provided for PDF export");
        return;
    }
    
    const doc = new jsPDF();
    const routeId = route._id ? route._id.toString().slice(-6).toUpperCase() : "UNKNOWN";
    const status = route.status ? route.status.toUpperCase() : "PENDING";
    const createdAt = route.createdAt ? new Date(route.createdAt).toLocaleString() : new Date().toLocaleString();

    // Title
    doc.setFontSize(20);
    doc.setTextColor(0, 102, 255); // FleetFlow Blue
    doc.text(`FleetFlow Route Plan #${routeId}`, 14, 22);
    
    // Route Info
    doc.setFontSize(11);
    doc.setTextColor(100);
    doc.text(`Created: ${createdAt}`, 14, 30);
    doc.text(`Status: ${status}`, 14, 36);
    doc.text(`Estimated Time: ${route.estimatedTime || 0} min`, 14, 42);
    
    // Financial Breakdown
    doc.setTextColor(16, 185, 129); // Green for Costs
    doc.text(`Fuel Cost: INR ${route.costBreakdown?.fuel?.toFixed(2) || '0.00'}`, 14, 48);
    doc.text(`Driver Wage: INR ${route.costBreakdown?.time?.toFixed(2) || '750.00'}`, 14, 54);
    doc.text(`Maint. Cost: INR ${route.costBreakdown?.maintenance?.toFixed(2) || '0.00'}`, 14, 60);
    
    doc.setTextColor(0, 102, 255); // Blue for Total
    doc.text(`Total Running Cost: INR ${route.costBreakdown?.total?.toFixed(2) || '0.00'}`, 14, 66);

    // Table Columns
    const tableColumn = ["Seq", "Address", "Priority", "Time Window", "Expected Arrival"];
    const tableRows = [];

    // Table Rows
    const stops = Array.isArray(route.route) ? route.route : [];
    stops.forEach((stop, index) => {
      const arrivalDate = route.createdAt ? new Date(route.createdAt) : new Date();
      const arrivalTime = new Date(arrivalDate.getTime() + index * 30 * 60000).toLocaleTimeString([], {hour: '2-digit', minute:'2-digit'});
      
      const stopData = [
        index + 1,
        stop.address || "Unknown Address",
        stop.priority || "normal",
        stop.timeWindow || "Anytime",
        arrivalTime
      ];
      tableRows.push(stopData);
    });

    if (doc.autoTable) {
      doc.autoTable({
        startY: 74,
        head: [tableColumn],
        body: tableRows,
        theme: 'grid',
        headStyles: { fillColor: [75, 192, 192] }, // FleetFlow teal color
      });
    }

    // Footer
    const pageCount = doc.internal.getNumberOfPages();
    for(let i = 1; i <= pageCount; i++) {
      doc.setPage(i);
      doc.setFontSize(10);
      doc.setTextColor(150);
      doc.text('Page ' + i + ' of ' + pageCount, 14, doc.internal.pageSize.height - 10);
      doc.text('Generated by FleetFlow - AI Logistics Optimizer', doc.internal.pageSize.width - 14, doc.internal.pageSize.height - 10, {align: 'right'});
    }

    doc.save(`fleetflow_route_${routeId}.pdf`);
  } catch (err) {
    console.error("Critical PDF Export Error:", err);
    alert("PDF generation failed. Please ensure the route has been fully optimized.");
  }
};

/**
 * Export route details to CSV
 * @param {Object} route - The route object
 */
export const exportToCSV = (route) => {
  try {
    const routeId = route?._id ? route._id.toString().slice(-6).toUpperCase() : "UNKNOWN";
    const headers = ["Sequence,Address,Priority,Time Window,Expected Arrival"];
    
    const stops = Array.isArray(route?.route) ? route.route : [];
    const rows = stops.map((stop, index) => {
      const arrivalDate = route.createdAt ? new Date(route.createdAt) : new Date();
      const arrivalTime = new Date(arrivalDate.getTime() + index * 30 * 60000).toLocaleTimeString([], {hour: '2-digit', minute:'2-digit'});
      return `${index + 1},"${stop.address || 'Unknown'}",${stop.priority || 'normal'},${stop.timeWindow || "Anytime"},${arrivalTime}`;
    });

    const csvContent = "data:text/csv;charset=utf-8," + [headers, ...rows].join("\n");
    const encodedUri = encodeURI(csvContent);
    const link = document.createElement("a");
    link.setAttribute("href", encodedUri);
    link.setAttribute("download", `fleetflow_route_${routeId}.csv`);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  } catch (err) {
    console.error("CSV Export Error:", err);
  }
};
